title: Zach Turski's GIS Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Zach Turski's GIS Portfolio
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "zach-tur.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zach Turski # add your name
author-img: zt-portrait.png # add your photo
about-author: >
  GIS Technician focused on geospatial applications provided through ArcGIS and other technologies.
  This portfolio is a work in progress as I search for a company to learn and grow with.
  Please see my LinkedIn for recent GIS work experience.
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: zach-tur # add your Github handle
social-linkedin: zachturski # add your Linkedin handle
# social-email: # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
